replicaCount: 2

image:
  repository: 061051239199.dkr.ecr.us-east-1.amazonaws.com/sentiment-api
  tag: v1.0
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 60
  periodSeconds: 30
